name: flutter_postman
description: Flutter Postman

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  auto_size_text: ^3.0.0
  firebase_auth: ^3.6.2
  firebase_core: ^1.20.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  http: ^0.13.5
  lottie: ^1.4.1
  shared_preferences: ^2.0.15
  uuid: ^3.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Regular.ttf
        - asset: fonts/Roboto-Black.ttf
          weight: 800
        - asset: fonts/Roboto-Bold.ttf
          weight: 700
        - asset: fonts/Roboto-Medium.ttf
          weight: 600