name: flutter_postman
description: Flutter Postman

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  accordion: ^2.5.1
  auto_size_text: ^3.0.0
  cloud_firestore: ^3.4.5
  dart_style: ^2.2.3
  data_table_2: ^2.3.6
  firebase_auth: ^3.6.2
  firebase_core: ^1.20.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  http: ^0.13.5
  json_ast: 
    git:
      url: https://github.com/matnex-mix/json_ast.git
      ref: master
  json_editor: ^0.0.8
  json_to_dart:
    git:
      url: https://github.com/syedmurtaza108/json_to_dart.git
      ref: master
  lottie: ^1.4.1
  lottie_player: ^0.0.5
  shared_preferences: ^2.0.15
  split_view: ^3.2.1
  uuid: ^3.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Regular.ttf
        - asset: fonts/Roboto-Black.ttf
          weight: 800
        - asset: fonts/Roboto-Bold.ttf
          weight: 700
        - asset: fonts/Roboto-Medium.ttf
          weight: 600
    - family: SourceCodePro
      fonts:
        - asset: fonts/SourceCodePro-Regular.ttf
        - asset: fonts/SourceCodePro-Black.ttf
          weight: 800
        - asset: fonts/SourceCodePro-Bold.ttf
          weight: 700
        - asset: fonts/SourceCodePro-Medium.ttf
          weight: 600