// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.fuchsia:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for fuchsia - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdSUsw9lTT21gLCQemWQrA45zB9P1Jczk',
    appId: '1:998672278480:web:c7f41fcc055fec656c4fd5',
    messagingSenderId: '998672278480',
    projectId: 'flutter-postman',
    authDomain: 'flutter-postman.firebaseapp.com',
    storageBucket: 'flutter-postman.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAx8C8OcEsi4XWxVTSoWZLjB5jFnnpHsSo',
    appId: '1:998672278480:android:1811585055095cd56c4fd5',
    messagingSenderId: '998672278480',
    projectId: 'flutter-postman',
    storageBucket: 'flutter-postman.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPSEi5EE8dCKMleFOpRQV023bMm5LsWCw',
    appId: '1:998672278480:ios:cb75214020c2493d6c4fd5',
    messagingSenderId: '998672278480',
    projectId: 'flutter-postman',
    storageBucket: 'flutter-postman.appspot.com',
    iosClientId: '998672278480-n063snf0micuao0q9so3nmbh03st6g04.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterPostman',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPSEi5EE8dCKMleFOpRQV023bMm5LsWCw',
    appId: '1:998672278480:ios:cb75214020c2493d6c4fd5',
    messagingSenderId: '998672278480',
    projectId: 'flutter-postman',
    storageBucket: 'flutter-postman.appspot.com',
    iosClientId: '998672278480-n063snf0micuao0q9so3nmbh03st6g04.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterPostman',
  );
}
